# Tensorflow

In [21]:
import tensorflow as tf

In [8]:
print(tf.version)

<module 'tensorflow._api.v2.version' from 'C:\\Users\\mirza\\anaconda3\\Lib\\site-packages\\tensorflow\\_api\\v2\\version\\__init__.py'>


In [17]:
string = tf.Variable("this is string",tf.string)
number = tf.Variable(565,tf.int64)
floating = tf.Variable(763.6353,tf.float64)

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'this is string'>


In [45]:
rank1_tensor = tf.Variable(['test'],tf.string)
rank2_tensor = tf.Variable([[['jbsd','jbsd'],['jbsd','sewe']]],tf.string)

In [47]:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [51]:
rank2_tensor.shape

TensorShape([1, 2, 2])

In [67]:
#creating tensor
tensor1 = tf.ones([1,2,3])
print(tensor1)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)


In [71]:
#reshaping tensor
tensor2 = tf.reshape(tensor1, [2,3,1])  #we cannot add more


In [73]:
tensor3 = tf.reshape(tensor2, [3,-1])  # -1 tells the tensor to calculate the size of the dimension in that place


In [87]:
print(tensor1)
print(  '\n'  )
print(tensor2)
print(  '\n'  )
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)


tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)


tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [93]:
#slicing tensor
matrix = [[1,2,3,4,5],
          [6,7,8,9,10],
          [11,12,13,14,15],
          [16,17,18,19,20]]
tensor = tf.Variable(matrix,dtype = tf.int32)
print(tf.rank(tensor)) 
print(tensor.shape)

#The tensor has a shape of (), meaning it is a scalar tensor.A scalar tensor contains a single value, so it has no dimensions.

tf.Tensor(2, shape=(), dtype=int32)
(4, 5)


In [95]:
three = tensor[0,2]
print(three)

tf.Tensor(3, shape=(), dtype=int32)


In [99]:
row1  = tensor[0]
print(row1)

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)


In [103]:
row2=tensor[1]
print(row2)

tf.Tensor([ 6  7  8  9 10], shape=(5,), dtype=int32)


In [105]:
col1 = tensor[:,0]
print(col1)

tf.Tensor([ 1  6 11 16], shape=(4,), dtype=int32)


In [107]:
col2 = tensor[:,1]
print(col2)

tf.Tensor([ 2  7 12 17], shape=(4,), dtype=int32)


In [123]:
row2and5 = tensor[1::2]
print(row2and5)

tf.Tensor(
[[ 6  7  8  9 10]
 [16 17 18 19 20]], shape=(2, 5), dtype=int32)
